### ISSUE TITLE
Weird visual behavior with water

### ISSUE THREAD

**Issue by DreamSt4n** [douira/sodium-fabric#13]
### Bug Description

This seems to happen most consistently on the world loading. It temporarily goes away when you are far enough away from the area.

![2023-12-23_22 33 13](https://github.com/douira/sodium-fabric/assets/19875208/26757b09-b82d-482a-82c8-da6656873a3d)

### Reproduction Steps

Step 1. Look at an ocean

### Attach Log File

No

### Attach Crash Report

No

**Comment by Felix14-v2** [comment]
Known issue, commits before [16c24cf](https://github.com/douira/sodium-fabric/commit/16c24cfbd6866b46b501865437c9ae098ceb72e8) (maybe excluding b96977b) are unaffected.

**Comment by douira** [comment]
Fixed
